# Wstęp do Uczenia Maszynowego - Projekt I
## Etap: Drugi Kamień Milowy 
### Autorzy: Krzysztof Osiński, Jakub Miszczak

## Import packages

In [1]:
import pandas as pd
import numpy as np
import sklearn 
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import warnings
warnings.filterwarnings('ignore')
np.random.seed(23)
import zipfile

# Fraud Detection Transactions Dataset - Feature Extraction

In [2]:
zip_path = "fraud-detection-transactions-dataset.zip"

with zipfile.ZipFile(zip_path, 'r') as z:
    with z.open("synthetic_fraud_dataset.csv") as file:
        df = pd.read_csv(file)

In [3]:
df.columns = df.columns.str.replace(" ","_").str.lower()
df1 = df.drop(['transaction_id','user_id'],axis='columns')
df1['timestamp'] = pd.to_datetime(df1['timestamp'])

## Variance Inflation Factor

Wartość VIF w okolicach 1 mówi o bardzo małej współliniowości cech.

In [5]:
X = df.drop('fraud_label', axis='columns')
y = df['fraud_label']

from sklearn.preprocessing import MinMaxScaler

scaled_columns = X.select_dtypes(['int64', 'float64']).columns

scaler = MinMaxScaler()

X[scaled_columns] = scaler.fit_transform(X[scaled_columns])
X.describe()

,transaction_amount,account_balance,ip_address_flag,previous_fraudulent_activity,daily_transaction_count,avg_transaction_amount_7d,failed_transaction_count_7d,card_age,transaction_distance,risk_score,is_weekend
count,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,0.084667,0.500449,0.05020,0.098400,0.498865,0.500555,0.500885,0.500000,0.499815,0.501506,0.299640
std,0.084051,0.289056,0.21836,0.297858,0.310741,0.288535,0.353568,0.289856,0.288421,0.287803,0.458105
min,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.024424,0.249810,0.00000,0.000000,0.230769,0.249158,0.250000,0.247899,0.251266,0.253925,0.000000
50%,0.059329,0.501357,0.00000,0.000000,0.461538,0.502214,0.500000,0.500000,0.498139,0.502200,0.000000
75%,0.118259,0.749912,0.00000,0.000000,0.769231,0.751087,0.750000,0.752101,0.749277,0.749500,1.000000
max,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calculate_vif(df):
    vif_df = pd.DataFrame()
    vif_df['Column'] = df.columns
    vif_df['VIF'] = [variance_inflation_factor(df.values,i) for i in range(df.shape[1])]
    return vif_df

In [7]:
calculate_vif(X[cols_to_scale])

                          Column       VIF
0             transaction_amount  1.927162
1                account_balance  3.461534
2                ip_address_flag  1.050360
3   previous_fraudulent_activity  1.103640
4        daily_transaction_count  3.159568
5      avg_transaction_amount_7d  3.472175
6    failed_transaction_count_7d  2.730906
7                       card_age  3.429442
8           transaction_distance  3.452925
9                     risk_score  3.478727
10                    is_weekend  1.399283